spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.92.156:3307/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: haoqi
  redis:
    host: 124.223.92.156
    port: 6379
    password: haoqi
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8102
haoqicodehub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5 #密钥
    expire: 604800 #token有效时长,7天,单位是秒
    header: Authorization
shiro-redis:
  enabled: true
  redis-manager:
    host: 124.223.92.156:6379
    password: haoqi
